// Regenerates sitemap.xml from the static page list plus every page the Notion
// generators produced. Runs last in the sync workflow so it can see both the
// blog and project manifests.
const fs = require('fs');
const { execFileSync } = require('child_process');
const { SITE, STATIC_PAGES, readManifest } = require('./lib/notion');

const POSTS_MANIFEST = '.generated-posts.json';
const PROJECTS_MANIFEST = '.generated-projects.json';

// <lastmod> values from the sitemap currently on disk, keyed by <loc>.
function previousLastmods() {
  const map = new Map();
  try {
    const xml = fs.readFileSync('sitemap.xml', 'utf8');
    for (const m of xml.matchAll(/<loc>([^<]+)<\/loc>\s*<lastmod>([^<]+)<\/lastmod>/g)) map.set(m[1], m[2]);
  } catch (e) { /* first run: no sitemap yet */ }
  return map;
}

// True when the file is committed and identical to HEAD.
function unchangedSinceCommit(file) {
  try {
    execFileSync('git', ['ls-files', '--error-unmatch', file], { stdio: 'ignore' });
    execFileSync('git', ['diff', '--quiet', 'HEAD', '--', file], { stdio: 'ignore' });
    return true;
  } catch (e) {
    return false;
  }
}

// Keep a page's previous <lastmod> unless the page itself changed in this run.
// File mtimes don't work here: CI checks out a fresh tree every hour, so every
// mtime is "now" and the sync committed a new sitemap each run, which also
// trains crawlers to ignore <lastmod>.
function lastmodFor(loc, file, previous, now) {
  return previous.has(loc) && unchangedSinceCommit(file) ? previous.get(loc) : now;
}

function buildSitemap() {
  const now = new Date().toISOString();
  const previous = previousLastmods();
  const withLastmod = (u, file) => ({ ...u, lastmod: lastmodFor(u.loc, file, previous, now) });

  const staticUrls = STATIC_PAGES.map(p => {
    const file = p.loc === `${SITE}/` ? 'index.html' : p.loc.replace(`${SITE}/`, '');
    return withLastmod(p, file);
  });

  const postUrls = readManifest(POSTS_MANIFEST).map(slug => withLastmod({
    loc: `${SITE}/${slug}.html`,
    changefreq: 'monthly',
    priority: '0.7',
  }, `${slug}.html`));

  const projectUrls = readManifest(PROJECTS_MANIFEST).map(slug => withLastmod({
    loc: `${SITE}/project-${slug}.html`,
    changefreq: 'monthly',
    priority: '0.7',
  }, `project-${slug}.html`));

  // Only list pages that actually exist on disk, so a half-finished sync can
  // never advertise a 404 to crawlers.
  const urls = [...staticUrls, ...postUrls, ...projectUrls].filter(u => {
    const file = u.loc === `${SITE}/` ? 'index.html' : u.loc.replace(`${SITE}/`, '');
    return fs.existsSync(file);
  });

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by build-sitemap.js. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map(u => `  <url>
    <loc>${u.loc}</loc>
    <lastmod>${u.lastmod}</lastmod>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`).join('\n')}
</urlset>
`;
}

if (require.main === module) {
  const xml = buildSitemap();
  fs.writeFileSync('sitemap.xml', xml);
  const count = (xml.match(/<url>/g) || []).length;
  console.log(`sitemap.xml written: ${count} URL(s).`);
}

module.exports = { buildSitemap };
